### PR TITLE
Define _jupyter_server_extension_paths for backward compatibility

### PR DESCRIPTION
**Pull request by casparvl**
Also, the `__init__.py` file used to contain 

```
load_jupyter_server_extension = load_jupyter_server_extension
```

That doesn't seem to make sense, it's like `x = x`, that's a no-op. Probably you meant to do what was suggested here https://jupyter-server.readthedocs.io/en/latest/developers/extensions.html#migrating-an-extension-to-use-jupyter-server , also for backward compatibility. 

For comparison, see e.g. https://github.com/jupyterhub/jupyter-server-proxy/blob/099fce21feed4c5c762740dea2d34c5ca548c5b3/jupyter_server_proxy/__init__.py#L51

### CODE REVIEW

**Comment by casparvl** [comment]
Ping on this one: is there anything blocking the merge of this fix?

**Comment by jtpio** [comment]
Thanks @casparvl this looks good :+1: 

Waiting for the CI fix to complete in https://github.com/jupyter-server/jupyter-resource-usage/pull/145. We can then rebase this PR and merge it.

**Comment by casparvl** [comment]
@jtpio I accidentally removed my fork for this. I saw you rebased my other PR based on #145 . Can you still do the same for thise one so that it can be merged? Or is that impossible now that more fork disappeared? If the 2nd: any suggestion on how we best proceed? It's a one-line change, if needed I can recreate it in a new fork (or you can, whichever you prefer)...

**Comment by jtpio** [comment]
@casparvl maybe the best would be to create a new branch on your fork with this change, and open a new PR.

**Comment by casparvl** [comment]
Closing in favour of https://github.com/jupyter-server/jupyter-resource-usage/pull/148

**Pull request closed without merging**
